### ISSUE TITLE
是否有支持自动生成函数工具库api文档的计划

### ISSUE THREAD

**Issue by yanc233** [dewfall123/ruabick#14]
在使用@ruabick/vlib脚手架创建 项目的时候有存在 ts-library 选项
但似乎实际上是一个空模板,是目前不支持吗?

**Comment by dewfall123** [comment]
最近没啥时间弄。之前研究过，参考arco-design只能自动生成ts文件中 Interface 的文档 ，感觉不是很满意。

**Comment by dewfall123** [comment]
我找时间把这个先加上
> 参考arco-design只能自动生成ts文件中 Interface 的文档

**Comment by dewfall123** [comment]
如下
 https://github.com/dewfall123/ruabick/issues/7#issuecomment-1315436615
